# Copyright (c) 2023, Kevin German

name: pianoman
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.*
  - cython
  - gcc
  - cmake
  - ninja
  - pytest
  - tox
  - versioneer>=0.29